name: CI

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              working-directory: frontend
              run: npm install

            - name: Run Linter
              working-directory: frontend
              run: npx eslint "src/**/*.{ts,tsx,js,jsx}"

            - name: Run tests
              working-directory: frontend
              run: npm run test
